# Invalid template names

amqp:
  exchange: exchange_name
  host: amqp_host
  password: guest
  port: 5672
  prefix: x
  routing_key: x
  ssl: false
  ssl_accept_all: false
  username: guest
  vhost: /

vcd:
  api_version: '31.0'
  host: 1.1.1.1
  log: true
  password: x
  port: 443
  username: x
  verify: false

vcs:
- name: x
  password: x
  username: x
  verify: false

service:
  listeners: 5

broker:
  catalog: cse # public shared catalog within org where the template will be published
  cse_msg_dir: /tmp/cse # not used
  default_template: ubuntu-16.04 # name of the default template to use if none is specified
  ip_allocation_mode: pool # dhcp or pool
  network: TestbedPG # org network within @vdc that will be used during the install process to build the template
                          # Should have outbound access to the public internet
                          # CSE appliance doesn't need to be connected to this network
  org: cseorg # vCD org that contains the shared catalog where the master templates will be stored
  storage_profile: '*' # name of the storage profile to use when creating the temporary vApp used to build the template
  templates:
  - admin_password: guest_os_admin_password
    catalog_item: bad_template1
    cleanup: false
    cpu: 2
    description: 'Ubuntu 16.04

      Docker 18.03.0~ce

      Kubernetes 1.10.1

      weave 2.3.0'
    mem: 2048
    name: ubuntu-16.04
    sha256_ova: 3c1bec8e2770af5b9b0462e20b7b24633666feedff43c099a6fb1330fcc869a9
    source_ova: https://cloud-images.ubuntu.com/releases/xenial/release-20180418/ubuntu-16.04-server-cloudimg-amd64.ova
    source_ova_name: ubuntu-16.04-server-cloudimg-amd64.ova
    temp_vapp: ubuntu1604-temp
  - admin_password: guest_os_admin_password
    catalog_item: bad_template2
    cleanup: false
    cpu: 2
    description: 'PhotonOS v2

      Docker 17.06.0-4

      Kubernetes 1.9.1

      weave 2.3.0'
    mem: 2048
    name: photon-v2
    sha256_ova: cb51e4b6d899c3588f961e73282709a0d054bb421787e140a1d80c24d4fd89e1
    source_ova: http://dl.bintray.com/vmware/photon/2.0/GA/ova/photon-custom-hw11-2.0-304b817.ova
    source_ova_name: photon-custom-hw11-2.0-304b817.ova
    temp_vapp: photon2-temp
  type: default
  vdc: cseorg-vdc # VDC within @org that will be used during the install process to build the template

