# coding: utf-8

"""
    API Specification for the Kubernetes on vSphere (KOV)

    # RESTful API for the Kubernetes on vSphere (KOV) 

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_add_user(self):
        """
        Test case for add_user

        adds a user to a cluster
        """
        pass

    def test_create_cluster(self):
        """
        Test case for create_cluster

        creates a cluster
        """
        pass

    def test_delete_cluster(self):
        """
        Test case for delete_cluster

        deletes a cluster
        """
        pass

    def test_get_task(self):
        """
        Test case for get_task

        get the task for the given task id
        """
        pass

    def test_get_user_config(self):
        """
        Test case for get_user_config

        retrieves the user kubeconfig
        """
        pass

    def test_list_clusters(self):
        """
        Test case for list_clusters

        get a list of all clusters
        """
        pass

    def test_list_task_i_ds(self):
        """
        Test case for list_task_i_ds

        get a list of task IDs
        """
        pass

    def test_logs_cluster(self):
        """
        Test case for logs_cluster

        fetches cluster logs
        """
        pass

    def test_update_cluster(self):
        """
        Test case for update_cluster

        updates a cluster
        """
        pass


if __name__ == '__main__':
    unittest.main()
