# coding: utf-8

"""
    API Specification for the Kubernetes on vSphere (KOV)

    # RESTful API for the Kubernetes on vSphere (KOV) 

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ClusterUpdateConfig(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, min_nodes=None, max_nodes=None, no_of_masters=1, storage_classes=None, ops_username=None, ops_password=None, authorized_keys=None):
        """
        ClusterUpdateConfig - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'min_nodes': 'int',
            'max_nodes': 'int',
            'no_of_masters': 'int',
            'storage_classes': 'list[StorageClass]',
            'ops_username': 'str',
            'ops_password': 'str',
            'authorized_keys': 'list[str]'
        }

        self.attribute_map = {
            'name': 'name',
            'min_nodes': 'minNodes',
            'max_nodes': 'maxNodes',
            'no_of_masters': 'noOfMasters',
            'storage_classes': 'storageClasses',
            'ops_username': 'opsUsername',
            'ops_password': 'opsPassword',
            'authorized_keys': 'authorizedKeys'
        }

        self._name = name
        self._min_nodes = min_nodes
        self._max_nodes = max_nodes
        self._no_of_masters = no_of_masters
        self._storage_classes = storage_classes
        self._ops_username = ops_username
        self._ops_password = ops_password
        self._authorized_keys = authorized_keys

    @property
    def name(self):
        """
        Gets the name of this ClusterUpdateConfig.
        the cluster name, should be valid for use in dns names

        :return: The name of this ClusterUpdateConfig.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ClusterUpdateConfig.
        the cluster name, should be valid for use in dns names

        :param name: The name of this ClusterUpdateConfig.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")
        if name is not None and not re.search('^[a-zA-Z](([-0-9a-zA-Z]+)?[0-9a-zA-Z])?(\\.[a-zA-Z](([-0-9a-zA-Z]+)?[0-9a-zA-Z])?)*$', name):
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^[a-zA-Z](([-0-9a-zA-Z]+)?[0-9a-zA-Z])?(\\.[a-zA-Z](([-0-9a-zA-Z]+)?[0-9a-zA-Z])?)*$/`")

        self._name = name

    @property
    def min_nodes(self):
        """
        Gets the min_nodes of this ClusterUpdateConfig.
        the minimum number of nodes that can be deployed

        :return: The min_nodes of this ClusterUpdateConfig.
        :rtype: int
        """
        return self._min_nodes

    @min_nodes.setter
    def min_nodes(self, min_nodes):
        """
        Sets the min_nodes of this ClusterUpdateConfig.
        the minimum number of nodes that can be deployed

        :param min_nodes: The min_nodes of this ClusterUpdateConfig.
        :type: int
        """
        if min_nodes is None:
            raise ValueError("Invalid value for `min_nodes`, must not be `None`")
        if min_nodes is not None and min_nodes < 1:
            raise ValueError("Invalid value for `min_nodes`, must be a value greater than or equal to `1`")

        self._min_nodes = min_nodes

    @property
    def max_nodes(self):
        """
        Gets the max_nodes of this ClusterUpdateConfig.
        the minimum number of nodes that can be deployed

        :return: The max_nodes of this ClusterUpdateConfig.
        :rtype: int
        """
        return self._max_nodes

    @max_nodes.setter
    def max_nodes(self, max_nodes):
        """
        Sets the max_nodes of this ClusterUpdateConfig.
        the minimum number of nodes that can be deployed

        :param max_nodes: The max_nodes of this ClusterUpdateConfig.
        :type: int
        """

        self._max_nodes = max_nodes

    @property
    def no_of_masters(self):
        """
        Gets the no_of_masters of this ClusterUpdateConfig.
        the number of master nodes to create

        :return: The no_of_masters of this ClusterUpdateConfig.
        :rtype: int
        """
        return self._no_of_masters

    @no_of_masters.setter
    def no_of_masters(self, no_of_masters):
        """
        Sets the no_of_masters of this ClusterUpdateConfig.
        the number of master nodes to create

        :param no_of_masters: The no_of_masters of this ClusterUpdateConfig.
        :type: int
        """
        if no_of_masters is not None and no_of_masters < 1:
            raise ValueError("Invalid value for `no_of_masters`, must be a value greater than or equal to `1`")

        self._no_of_masters = no_of_masters

    @property
    def storage_classes(self):
        """
        Gets the storage_classes of this ClusterUpdateConfig.

        :return: The storage_classes of this ClusterUpdateConfig.
        :rtype: list[StorageClass]
        """
        return self._storage_classes

    @storage_classes.setter
    def storage_classes(self, storage_classes):
        """
        Sets the storage_classes of this ClusterUpdateConfig.

        :param storage_classes: The storage_classes of this ClusterUpdateConfig.
        :type: list[StorageClass]
        """

        self._storage_classes = storage_classes

    @property
    def ops_username(self):
        """
        Gets the ops_username of this ClusterUpdateConfig.

        :return: The ops_username of this ClusterUpdateConfig.
        :rtype: str
        """
        return self._ops_username

    @ops_username.setter
    def ops_username(self, ops_username):
        """
        Sets the ops_username of this ClusterUpdateConfig.

        :param ops_username: The ops_username of this ClusterUpdateConfig.
        :type: str
        """
        if ops_username is None:
            raise ValueError("Invalid value for `ops_username`, must not be `None`")
        if ops_username is not None and len(ops_username) < 1:
            raise ValueError("Invalid value for `ops_username`, length must be greater than or equal to `1`")

        self._ops_username = ops_username

    @property
    def ops_password(self):
        """
        Gets the ops_password of this ClusterUpdateConfig.

        :return: The ops_password of this ClusterUpdateConfig.
        :rtype: str
        """
        return self._ops_password

    @ops_password.setter
    def ops_password(self, ops_password):
        """
        Sets the ops_password of this ClusterUpdateConfig.

        :param ops_password: The ops_password of this ClusterUpdateConfig.
        :type: str
        """
        if ops_password is None:
            raise ValueError("Invalid value for `ops_password`, must not be `None`")
        if ops_password is not None and len(ops_password) < 1:
            raise ValueError("Invalid value for `ops_password`, length must be greater than or equal to `1`")

        self._ops_password = ops_password

    @property
    def authorized_keys(self):
        """
        Gets the authorized_keys of this ClusterUpdateConfig.
        the public keys that should get root ssh access to the nodes

        :return: The authorized_keys of this ClusterUpdateConfig.
        :rtype: list[str]
        """
        return self._authorized_keys

    @authorized_keys.setter
    def authorized_keys(self, authorized_keys):
        """
        Sets the authorized_keys of this ClusterUpdateConfig.
        the public keys that should get root ssh access to the nodes

        :param authorized_keys: The authorized_keys of this ClusterUpdateConfig.
        :type: list[str]
        """

        self._authorized_keys = authorized_keys

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ClusterUpdateConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
