broker:
  catalog: cse
  default_template_name: ubuntu-16.04_k8-1.21_weave-2.8.1
  default_template_revision: 1
  ip_allocation_mode: pool
  network: csenet
  org: cseorg
  remote_template_cookbook_url: http://raw.githubusercontent.com/vmware/container-service-extension-templates/dev/template_v2.yaml
  storage_profile: '*'
  vdc: cseorgvdc
mqtt:
  verify_ssl: false
service:
  enforce_authorization: false
  legacy_mode: false
  log_wire: false
  no_vc_communication_mode: false
  processors: 5
  telemetry:
    enable: false
vcd:
  host: bos1-vcloud-static-173-31.eng.vmware.com
  log: true
  password: ca$hc0w
  port: 443
  username: administrator
  verify: false
vcs:
- name: vc1
  password: Welcome@123
  username: administrator@vsphere.local
  verify: false
