# coding: utf-8

# flake8: noqa
"""
    PKS

    PKS API  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from container_service_extension.lib.pksclient.models.kubernetes_settings import KubernetesSettings # noqa: E501
