# coding: utf-8

"""
    PKS

    PKS API  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CustomCaCert(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domain_name': 'str',
        'ca_cert': 'str'
    }

    attribute_map = {
        'domain_name': 'domain_name',
        'ca_cert': 'ca_cert'
    }

    def __init__(self, domain_name=None, ca_cert=None):  # noqa: E501
        """CustomCaCert - a model defined in Swagger"""  # noqa: E501

        self._domain_name = None
        self._ca_cert = None
        self.discriminator = None

        if domain_name is not None:
            self.domain_name = domain_name
        if ca_cert is not None:
            self.ca_cert = ca_cert

    @property
    def domain_name(self):
        """Gets the domain_name of this CustomCaCert.  # noqa: E501

        Domain name allows [a-zA-Z0-9_] in surroundings and [-.] in the middle. It also allows port in the end.  # noqa: E501

        :return: The domain_name of this CustomCaCert.  # noqa: E501
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name):
        """Sets the domain_name of this CustomCaCert.

        Domain name allows [a-zA-Z0-9_] in surroundings and [-.] in the middle. It also allows port in the end.  # noqa: E501

        :param domain_name: The domain_name of this CustomCaCert.  # noqa: E501
        :type: str
        """
        if domain_name is not None and not re.search(r'^([a-zA-Z0-9_](\\-|\\.)?)*[a-zA-Z0-9_]+(:[0-9]+)?$', domain_name):  # noqa: E501
            raise ValueError(r"Invalid value for `domain_name`, must be a follow pattern or equal to `/^([a-zA-Z0-9_](\\-|\\.)?)*[a-zA-Z0-9_]+(:[0-9]+)?$/`")  # noqa: E501

        self._domain_name = domain_name

    @property
    def ca_cert(self):
        """Gets the ca_cert of this CustomCaCert.  # noqa: E501


        :return: The ca_cert of this CustomCaCert.  # noqa: E501
        :rtype: str
        """
        return self._ca_cert

    @ca_cert.setter
    def ca_cert(self, ca_cert):
        """Sets the ca_cert of this CustomCaCert.


        :param ca_cert: The ca_cert of this CustomCaCert.  # noqa: E501
        :type: str
        """

        self._ca_cert = ca_cert

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomCaCert, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomCaCert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
